import { Client } from "./types";

export const MOCK_CLIENTS: Client[] = [
  {
    id: "TC-101",
    buyerName: "Rajesh Kumar",
    mobile: "9876543210",
    siteLocation: "Coimbatore",
    quantity: 120,
    rate: 1250,
    boundaryHeight: 8,
    notes: "Residential enclave outer security wall boundary.",
  },
  {
    id: "TC-102",
    buyerName: "Ananya Deshmukh",
    mobile: "9123456789",
    siteLocation: "pune",
    quantity: 350,
    rate: 1400,
    boundaryHeight: 6,
    notes: "Industrial warehouse partition boundaries.",
  },
  {
    id: "TC-103",
    buyerName: "Karthik Raja (VK Builders)",
    mobile: "8877665544",
    siteLocation: "Chennai",
    quantity: 80,
    rate: 1600,
    boundaryHeight: 10,
    notes: "High-security substation precast panels.",
  },
  {
    id: "TC-104",
    buyerName: "Mehta Constructions Ltd.",
    mobile: "9900112233",
    siteLocation: "Mumbai",
    quantity: 1200,
    rate: 1150,
    boundaryHeight: 8,
    notes: "Mass housing corridor, dual-finish texture panels.",
  },
  {
    id: "TC-105",
    buyerName: "Gopalakrishnan Nair",
    mobile: "9447012345",
    siteLocation: "Kochi",
    quantity: 240,
    rate: 1350,
    boundaryHeight: 6,
    notes: "Farmhouse containment wire-topped boundary.",
  },
  {
    id: "TC-106",
    buyerName: "Siddharth Hegde",
    mobile: "8050123456",
    siteLocation: "Bengaluru",
    quantity: 480,
    rate: 1500,
    boundaryHeight: 8,
    notes: "Tech park campus rear perimeter wall.",
  },
  {
    id: "TC-107",
    buyerName: "Rao Infrastructure",
    mobile: "9000190002",
    siteLocation: "Hyderabad",
    quantity: 2100,
    rate: 1100,
    boundaryHeight: 8,
    notes: "NHAI Bypass noise barrier precast modules.",
  },
  {
    id: "TC-108",
    buyerName: "Vikram Rathore",
    mobile: "7771234567",
    siteLocation: "Jaipur",
    quantity: 160,
    rate: 1450,
    boundaryHeight: 6,
    notes: "Eco-resort boundary with stone-textured precast.",
  },
  {
    id: "TC-109",
    buyerName: "Arunachal Developers",
    mobile: "9898989898",
    siteLocation: "Guwahati",
    quantity: 800,
    rate: 1300,
    boundaryHeight: 8,
    notes: "Border storage depot safety separation wall.",
  },
  {
    id: "TC-110",
    buyerName: "Sanjay Patel",
    mobile: "9825098250",
    siteLocation: "Ahmedabad",
    quantity: 400,
    rate: 1250,
    boundaryHeight: 6,
    notes: "Textile industrial compounding wall block.",
  },
  {
    id: "TC-111",
    buyerName: "L&T Smart Sites (Phase-1)",
    mobile: "9111222333",
    siteLocation: "Chennai",
    quantity: 3500,
    rate: 1050,
    boundaryHeight: 10,
    notes: "Massive smart city perimeter infrastructure.",
  },
  {
    id: "TC-112",
    buyerName: "Preethi Sridhar",
    mobile: "9600012345",
    siteLocation: "Coimbatore",
    quantity: 90,
    rate: 1550,
    boundaryHeight: 8,
    notes: "Villa compounding wall with timber texture.",
  },
  {
    id: "TC-113",
    buyerName: "Balaji Steels Corp",
    mobile: "9543210987",
    siteLocation: "Madurai",
    quantity: 180,
    rate: 1300,
    boundaryHeight: 8,
    notes: "Scrap yard partition heavy-duty retaining slab.",
  },
  {
    id: "TC-114",
    buyerName: "Gadkari Roadways Project",
    mobile: "8888877777",
    siteLocation: "Nagpur",
    quantity: 1500,
    rate: 1200,
    boundaryHeight: 8,
    notes: "Prestressed columns and solid brickwork look precast.",
  },
  {
    id: "TC-115",
    buyerName: "Venkateswara Farms",
    mobile: "9444455555",
    siteLocation: "Vijayawada",
    quantity: 320,
    rate: 1400,
    boundaryHeight: 6,
    notes: "Coconut grove perimeter wall with column caps.",
  },
  {
    id: "TC-116",
    buyerName: "Shree Ji Builders",
    mobile: "7000120003",
    siteLocation: "Indore",
    quantity: 640,
    rate: 1280,
    boundaryHeight: 8,
    notes: "Apartment complex phase 2 layout fencing.",
  },
  {
    id: "TC-117",
    buyerName: "Kolkata Port Terminal",
    mobile: "9330011223",
    siteLocation: "Kolkata",
    quantity: 1600,
    rate: 1350,
    boundaryHeight: 10,
    notes: "Salt-resistant cement based coastal precast panels.",
  },
  {
    id: "TC-118",
    buyerName: "Suresh & Brothers Nursery",
    mobile: "9090980808",
    siteLocation: "Bengaluru",
    quantity: 280,
    rate: 1420,
    boundaryHeight: 6,
    notes: "Low-height grid design panel boundary wall.",
  },
  {
    id: "TC-119",
    buyerName: "Elite Enclave Housing Group",
    mobile: "9810098100",
    siteLocation: "Delhi",
    quantity: 500,
    rate: 1650,
    boundaryHeight: 8,
    notes: "Brick-cast luxury finish precast panels.",
  },
  {
    id: "TC-120",
    buyerName: "Malabar Green Estates",
    mobile: "9846055443",
    siteLocation: "Kochi",
    quantity: 720,
    rate: 1380,
    boundaryHeight: 8,
    notes: "Weatherproof high-durability estate layout wall.",
  },
  {
    id: "TC-121",
    buyerName: "Adani Logistics Hub",
    mobile: "9212134345",
    siteLocation: "Ahmedabad",
    quantity: 2200,
    rate: 1100,
    boundaryHeight: 10,
    notes: "High-density heavy industrial zone security wall.",
  },
  {
    id: "TC-122",
    buyerName: "Ramalinga Swamy",
    mobile: "9488820000",
    siteLocation: "Salem",
    quantity: 110,
    rate: 1320,
    boundaryHeight: 8,
    notes: "Private township layout boundary.",
  },
];
